---
title: "Corona Virus Report"
author:
- familyname: Sun
  othernames: Miaomiao~
  address: Monash Universtidy
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
- familyname: Shi
  othernames: Jingyi
  address: Monash
  qualifications: XXX
- familyname: XXX
  othernames: XXX
  address: XXX
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
department: Our consultancy \newline add names &\newline add names
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)

```


\section*{Country Australia and Italy"}

```{r}
Australia_data <- worldwidecases %>% 
  filter( countriesAndTerritories == "Australia") %>% 
  select(dateRep,cases,deaths,countriesAndTerritories,month)

Italy_data <- worldwidecases %>% 
  filter( countriesAndTerritories == "Italy")%>% 
  select(dateRep,cases,deaths,countriesAndTerritories,month) %>% 
  rbind(Australia_data)

All_data <- Italy_data %>% 
  rbind(Australia_data) %>% 
  rename("Date" = "dateRep",
         "Country" = "countriesAndTerritories") 

Mean_monthdata <- All_data %>% 
 group_by(Country) %>%
  group_by(month) %>% 
  mutate(Month_case= mean(cases),
            Month_death = mean(deaths)) %>% 
  filter(Date %in% c("10/05/2020",
                     "30/04/2020",
                     "31/03/2020",
                     "29/02/2020",
                     "31/01/2020")) %>% 
  select(-Date)

Mean_monthdata %>% 
  head(10) %>% 
  kable(caption = "Summary of average data on new cases and deaths in Italy and Australia.")
```

```{r}

ggplot(Mean_monthdata,
             aes(x = month ))+
  geom_bar(aes(y = Month_case),stat="identity",
           fill="#69b3a2")+
  geom_line(aes(y=Month_death),
            color="#E69F00",
            size=1)+
  geom_point(aes(y=Month_death),
             color="#E69F00",
             size=2)+
  scale_y_continuous(name = "Cases",
                     sec.axis = sec_axis(trans =~./100,
                        name = "Death"))+
  theme(axis.text.x = element_text(angle = 90))+
   facet_grid(rows = vars(Country),scales = "free_y")
```

\section*{Country XX2 and YY2}
```{r}
worldcase <- read.csv("Data/worldwidecases.csv")

CHN_USA <- worldcase %>% 
  filter(countryterritoryCode %in% 
           c("CHN", "USA")) 
CHN_USA %>% 
  group_by(countriesAndTerritories) %>% 
  summarise(total_death = sum(deaths), 
            total_case = sum(cases),
            death_rate = total_death/total_case*100) %>% 
  kable(caption = "Death rate for China and USA")
```

```{r}
  ggplot(CHN_USA) +
  geom_line(mapping = 
              aes(x = dateRep,
                  y = cases,
                  color = countryterritoryCode)) +
  facet_wrap(~countryterritoryCode)
```

\section*{Country XX3 and YY3}







































```{r}
Assignment3_data <- read_csv("Data/Assignment3_data.csv")
Choose <- Assignment3_data %>% 
  filter(Country_Name %in% c("Australia","New Zealand"))
```




```{r}
Assignment3_data <- read_csv("Data/Assignment3_data.csv")
Choose <- Assignment3_data %>% 
  filter(Country_Name %in% c("Australia","New Zealand"))
```


